[package]
name = "music_selection"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
regex = "1.0"
rand = "0.8"
